# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

category:
  url:      /category/:slug
  class:    sfDoctrineRoute
  param:    { module: category, action: show }
  options:  { model: JobeetCategory, type: object }
  
job:
  class:   sfDoctrineRouteCollection
  options: { model: JobeetJob }

job_show_user:
  url:   /job/:company_slug/:location_slug/:id/:position_slug
  #class: sfRequestRoute
  class: sfDoctrineRoute
  options:
    model: JobeetJob
    type: object
    method_for_query: retrieveActiveJob
  param: { module: job, action: show }
  requirements:
    id: \d+
    sf_method: [get]
# default rules
homepage:
  url:   /
 # param: { module: default, action: index }
  param: { module: job, action: index }
# generic rules
# please, remove them by adding more specific rules
#default_index:
  # :module variable which represent something 
  # that can be returned by $request->getParameter('module')
 # url:   /:module 
  # default param
 # param: { action: index }

#default:
#  url:   /:module/:action/*
